### PR TITLE
Balagso Website

### PR DESCRIPTION
**Pull request by benjiruu12**
Please check my website before merging into the Main branch

### CODE REVIEW

**Review by nicktrr — APPROVED** [review]
awa pwede pwede

**Review by UBALDO17 — APPROVED** [review]
Goods!

**Review by asantiano — APPROVED** [review]
Okay na boss

**Review by pudge00 — APPROVED** [review]
All goods

**Review by asantiano — APPROVED** [review]
Okay na bossing

**Review by donutt18 — APPROVED** [review]
好工作

**Pull request merged**
